# -*- coding: utf-8 -*-
"""Markov Decision Processes (MDPs) and Bellman Equations and Value Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QF44e1JqaCXIeaIaDKLFf-A80Gu3KL-n
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

class GridWorld:
    def __init__(self, grid_size=5, gamma=0.9):
        self.grid_size = grid_size
        self.gamma = gamma
        self.policy = np.zeros((self.grid_size, self.grid_size), dtype=int)

        # Define the state space
        self.state_space = [(i, j) for i in range(grid_size) for j in range(grid_size)]
        self.state_size = len(self.state_space)

        # Define the action space
        self.action_space = ['UP', 'RIGHT', 'DOWN', 'LEFT']
        self.action_size = len(self.action_space)

        # Initialize the value function
        self.V = np.zeros((grid_size, grid_size))
        self.Q = np.zeros((grid_size, grid_size, self.action_size))

    def step(self, state, action):
        i, j = state

        # Define the reward function
        if state == (0, 1):
            return (0, 1), 10  # Stay in terminal state with reward
        elif state == (0, 3):
            return (0, 3), 5   # Stay in terminal state with reward
        else:
            if action == 0:  # 'UP'
                new_state = (max(0, i-1), j)
            elif action == 1:  # 'RIGHT'
                new_state = (i, min(self.grid_size-1, j+1))
            elif action == 2:  # 'DOWN'
                new_state = (min(self.grid_size-1, i+1), j)
            elif action == 3:  # 'LEFT'
                new_state = (i, max(0, j-1))
            else:
                return state, -1    #-1 reward for illegal action
            
            # Check if we reached a goal state
            if new_state == (0, 1):
                return new_state, 10
            elif new_state == (0, 3):
                return new_state, 5
            else:
                return new_state, -0.1  # Small negative reward for each step

    def reset(self):
        """Reset to a random starting position"""
        i = np.random.randint(0, self.grid_size)
        j = np.random.randint(0, self.grid_size)
        return (i, j)

    def is_terminal(self, state):
        """Check if state is terminal"""
        return state == (0, 1) or state == (0, 3)

    # 1. VALUE ITERATION (Dynamic Programming)
    def value_iteration(self, max_iterations=1000, tolerance=1e-6):
        """Solve MDP using Value Iteration"""
        print("Running Value Iteration...")
        for iteration in range(max_iterations):
            old_V = self.V.copy()
            
            for i in range(self.grid_size):
                for j in range(self.grid_size):
                    if self.is_terminal((i, j)):
                        continue
                    
                    max_value = float('-inf')
                    for action in range(self.action_size):
                        (next_i, next_j), reward = self.step((i, j), action)
                        value = reward + self.gamma * old_V[next_i, next_j]
                        max_value = max(max_value, value)
                    
                    self.V[i, j] = max_value
            
            # Check convergence
            if np.max(np.abs(self.V - old_V)) < tolerance:
                print(f"Value Iteration converged after {iteration + 1} iterations")
                break
        
        self._extract_policy()
        return self.V.copy()

    # 2. POLICY ITERATION (Dynamic Programming)
    def policy_iteration(self, max_iterations=100):
        """Solve MDP using Policy Iteration"""
        print("Running Policy Iteration...")
        
        # Initialize random policy
        for i in range(self.grid_size):
            for j in range(self.grid_size):
                self.policy[i, j] = np.random.randint(0, self.action_size)
        
        for iteration in range(max_iterations):
            # Policy Evaluation
            self._policy_evaluation()
            
            # Policy Improvement
            policy_stable = self._policy_improvement()
            
            if policy_stable:
                print(f"Policy Iteration converged after {iteration + 1} iterations")
                break
        
        return self.V.copy()

    # 3. Q-LEARNING (Model-Free)
    def q_learning(self, episodes=1000, alpha=0.1, epsilon=0.1):
        """Q-Learning algorithm with progress tracking"""
        print(f"Running Q-Learning for {episodes} episodes...")
        self.Q = np.zeros((self.grid_size, self.grid_size, self.action_size))
        
        rewards_per_episode = []
        progress_interval = max(1, episodes // 10)  # Show progress 10 times
        
        for episode in range(episodes):
            state = self.reset()
            total_reward = 0
            steps = 0
            max_steps = 50  # Reduced from 100 for faster execution
            
            while not self.is_terminal(state) and steps < max_steps:
                i, j = state
                
                # Epsilon-greedy action selection
                if np.random.random() < epsilon:
                    action = np.random.randint(0, self.action_size)
                else:
                    action = np.argmax(self.Q[i, j, :])
                
                # Take action
                next_state, reward = self.step(state, action)
                next_i, next_j = next_state
                
                # Q-Learning update
                if self.is_terminal(next_state):
                    target = reward
                else:
                    target = reward + self.gamma * np.max(self.Q[next_i, next_j, :])
                
                self.Q[i, j, action] += alpha * (target - self.Q[i, j, action])
                
                state = next_state
                total_reward += reward
                steps += 1
            
            rewards_per_episode.append(total_reward)
            
            # Show progress
            if episode % progress_interval == 0:
                avg_reward = np.mean(rewards_per_episode[-100:]) if len(rewards_per_episode) >= 100 else np.mean(rewards_per_episode)
                print(f"  Episode {episode}/{episodes}, Avg Reward: {avg_reward:.2f}, Epsilon: {epsilon:.3f}")
            
            # Decay epsilon more frequently
            if episode % 100 == 0 and epsilon > 0.01:
                epsilon *= 0.99
        
        print("Q-Learning completed!")
        
        # Extract value function from Q-values
        self.V = np.max(self.Q, axis=2)
        self._extract_policy_from_q()
        
        return rewards_per_episode

    # 4. TEMPORAL DIFFERENCE LEARNING (TD)
    def td_learning(self, episodes=1000, alpha=0.1):
        """TD(0) Learning for policy evaluation with progress tracking"""
        print(f"Running TD Learning for {episodes} episodes...")
        self.V = np.random.random((self.grid_size, self.grid_size)) * 0.1
        
        progress_interval = max(1, episodes // 10)
        
        # Use a random policy for evaluation
        for episode in range(episodes):
            state = self.reset()
            steps = 0
            max_steps = 50  # Reduced for faster execution
            
            while not self.is_terminal(state) and steps < max_steps:
                i, j = state
                
                # Random policy
                action = np.random.randint(0, self.action_size)
                
                # Take action
                next_state, reward = self.step(state, action)
                next_i, next_j = next_state
                
                # TD update
                if self.is_terminal(next_state):
                    target = reward
                else:
                    target = reward + self.gamma * self.V[next_i, next_j]
                
                self.V[i, j] += alpha * (target - self.V[i, j])
                
                state = next_state
                steps += 1
            
            # Show progress
            if episode % progress_interval == 0:
                max_value = np.max(self.V)
                print(f"  Episode {episode}/{episodes}, Max Value: {max_value:.3f}")
        
        print("TD Learning completed!")
        return self.V.copy()

    # Helper methods
    def _policy_evaluation(self, tolerance=1e-6, max_iterations=1000):
        """Evaluate current policy"""
        for iteration in range(max_iterations):
            old_V = self.V.copy()
            
            for i in range(self.grid_size):
                for j in range(self.grid_size):
                    if self.is_terminal((i, j)):
                        continue
                    
                    action = self.policy[i, j]
                    (next_i, next_j), reward = self.step((i, j), action)
                    self.V[i, j] = reward + self.gamma * old_V[next_i, next_j]
            
            if np.max(np.abs(self.V - old_V)) < tolerance:
                break

    def _policy_improvement(self):
        """Improve policy based on current value function"""
        policy_stable = True
        
        for i in range(self.grid_size):
            for j in range(self.grid_size):
                if self.is_terminal((i, j)):
                    continue
                
                old_action = self.policy[i, j]
                
                # Find best action
                best_value = float('-inf')
                best_action = 0
                
                for action in range(self.action_size):
                    (next_i, next_j), reward = self.step((i, j), action)
                    value = reward + self.gamma * self.V[next_i, next_j]
                    
                    if value > best_value:
                        best_value = value
                        best_action = action
                
                self.policy[i, j] = best_action
                
                if old_action != best_action:
                    policy_stable = False
        
        return policy_stable

    def _extract_policy(self):
        """Extract policy from value function"""
        for i in range(self.grid_size):
            for j in range(self.grid_size):
                if self.is_terminal((i, j)):
                    continue
                
                best_value = float('-inf')
                best_action = 0
                
                for action in range(self.action_size):
                    (next_i, next_j), reward = self.step((i, j), action)
                    value = reward + self.gamma * self.V[next_i, next_j]
                    
                    if value > best_value:
                        best_value = value
                        best_action = action
                
                self.policy[i, j] = best_action

    def _extract_policy_from_q(self):
        """Extract policy from Q-values"""
        for i in range(self.grid_size):
            for j in range(self.grid_size):
                self.policy[i, j] = np.argmax(self.Q[i, j, :])

    # VISUALIZATION METHODS
    def visualize_value_function(self, title="Value Function"):
        """Visualize the value function"""
        plt.figure(figsize=(8, 6))
        sns.heatmap(self.V, annot=True, fmt='.2f', cmap='viridis', 
                   cbar_kws={'label': 'Value'})
        plt.title(title)
        plt.ylabel('Row')
        plt.xlabel('Column')
        
        # Mark special states
        plt.text(1.5, 0.5, 'GOAL\n+10', ha='center', va='center', 
                color='red', fontweight='bold')
        plt.text(3.5, 0.5, 'GOAL\n+5', ha='center', va='center', 
                color='orange', fontweight='bold')
        
        plt.tight_layout()
        plt.show()

    def visualize_policy(self, title="Optimal Policy"):
        """Visualize the policy with arrows"""
        fig, ax = plt.subplots(figsize=(8, 6))
        
        # Create a colormap for the value function background
        im = ax.imshow(self.V, cmap='viridis', alpha=0.3)
        
        # Arrow directions
        arrows = ['↑', '→', '↓', '←']
        
        for i in range(self.grid_size):
            for j in range(self.grid_size):
                if self.is_terminal((i, j)):
                    ax.text(j, i, 'GOAL', ha='center', va='center', 
                           fontweight='bold', color='red')
                else:
                    ax.text(j, i, arrows[self.policy[i, j]], 
                           ha='center', va='center', fontsize=20)
        
        ax.set_xlim(-0.5, self.grid_size - 0.5)
        ax.set_ylim(-0.5, self.grid_size - 0.5)
        ax.set_xticks(range(self.grid_size))
        ax.set_yticks(range(self.grid_size))
        ax.set_xlabel('Column')
        ax.set_ylabel('Row')
        ax.set_title(title)
        
        # Add colorbar
        plt.colorbar(im, ax=ax, label='Value')
        plt.tight_layout()
        plt.show()

    def compare_algorithms(self):
        """Compare different RL algorithms"""
        algorithms = {}
        
        # Value Iteration
        self.V = np.zeros((self.grid_size, self.grid_size))
        vi_values = self.value_iteration()
        algorithms['Value Iteration'] = vi_values.copy()
        
        # Policy Iteration
        self.V = np.zeros((self.grid_size, self.grid_size))
        pi_values = self.policy_iteration()
        algorithms['Policy Iteration'] = pi_values.copy()
        
        # Q-Learning
        self.V = np.zeros((self.grid_size, self.grid_size))
        q_rewards = self.q_learning(episodes=10000)  # Reduced from 3000
        algorithms['Q-Learning'] = self.V.copy()
        
        # Visualize comparison
        fig, axes = plt.subplots(1, 3, figsize=(15, 4))
        
        for idx, (name, values) in enumerate(algorithms.items()):
            sns.heatmap(values, annot=True, fmt='.2f', cmap='viridis', 
                       ax=axes[idx], cbar_kws={'label': 'Value'})
            axes[idx].set_title(f'{name}')
            axes[idx].set_ylabel('Row')
            axes[idx].set_xlabel('Column')
        
        plt.tight_layout()
        plt.show()
        
        # Plot Q-Learning rewards
        if len(q_rewards) > 0:
            plt.figure(figsize=(10, 6))
            # Moving average for smoother plotting
            window = 100
            moving_avg = np.convolve(q_rewards, np.ones(window)/window, mode='valid')
            plt.plot(moving_avg)
            plt.title('Q-Learning: Average Reward per Episode')
            plt.xlabel('Episode')
            plt.ylabel('Average Reward')
            plt.grid(True)
            plt.show()

# TESTING FRAMEWORK
def test_rl_algorithms():
    """Complete testing framework for RL algorithms"""
    print("=== GridWorld RL Testing Framework ===\n")
    
    # Create environment
    env = GridWorld(grid_size=5, gamma=0.9)
    
    print("Environment Setup:")
    print(f"Grid Size: {env.grid_size}x{env.grid_size}")
    print(f"Discount Factor: {env.gamma}")
    print(f"Goal States: (0,1) with reward +10, (0,3) with reward +5")
    print(f"Action Space: {env.action_space}")
    print("\n" + "="*50 + "\n")
    
    # Compare all algorithms
    env.compare_algorithms()
    
    return env

# Run the testing framework
if __name__ == "__main__":
    env = test_rl_algorithms()
    
    # Additional individual tests
    print("\n=== Individual Algorithm Testing ===\n")
    
    # Test Value Iteration
    env_vi = GridWorld(grid_size=5, gamma=0.9)
    env_vi.value_iteration()
    env_vi.visualize_value_function("Value Iteration - Value Function")
    env_vi.visualize_policy("Value Iteration - Optimal Policy")
    
    # Test Q-Learning with learning curve
    env_ql = GridWorld(grid_size=5, gamma=0.9)
    rewards = env_ql.q_learning(episodes=1000)  # Reduced from 5000
    env_ql.visualize_value_function("Q-Learning - Learned Value Function")
    env_ql.visualize_policy("Q-Learning - Learned Policy")