# -*- coding: utf-8 -*-
"""Value Function Approximation using CartPole.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLuRNFua_euflEMTt96B9Jzr4vEG5gNA
"""


"""# Value Function Approximation using CartPole"""

import gymnasium as gym
import numpy as np

# Create the CartPole environment
env = gym.make('CartPole-v1')

# Initialize weights for our linear function approximator
weights = np.random.rand(4)

def policy(state):
    # Our simple policy: lean to the left when pole is leaning to the left, and vice versa
    return 0 if state[2] < 0 else 1

def value_function(state):
    # Our linear value function
    return np.dot(state, weights)

def update_weights(state, target, alpha=0.01):
    # Update the weights using stochastic gradient descent
    global weights
    weights += alpha * (target - value_function(state)) * state

# Initialize discount factor and number of episodes
gamma = 0.99
num_episodes = 5000

for i_episode in range(num_episodes):
    state = env.reset()
    done = False
    while not done:
        action = policy(state)
        next_state, reward, done, info = env.step(action)
        # Estimate the target value using the immediate reward and estimated future returns
        target = reward + gamma * value_function(next_state)
        update_weights(state, target)
        state = next_state

    if i_episode % 500 == 0:
        print(f"Episode {i_episode}, weights: {weights}")

print(f"Final weights: {weights}")